name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN}}
        repository: ${{github.repository}}
    - name: SSH into server and execute commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME}}
        password: ${{ secrets.SERVER_PASSWORD}}
        script: |
          git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/phamtungthuy/chat_real_time.git
          cd ${{ secrets.WORK_DIR }}
          git checkout master
          git pull origin master
          docker-compose up --build -d
          
